version: '3'
services:
  nestjs-service:
    image: ngthminhdev/stock-docker-hub:${TAG}
    deploy:
      replicas: 1
    ports: 
      - '3001:3001'
    environment:
      - CONFIG_SERVER_HOST=192.168.15.181
      - CONFIG_SERVER_PORT=3000
      - CONFIG_API_PREFIX=api/v1
      - CONFIG_STRATEGY=jwt
      - CONFIG_MSSQL_HOST=192.168.15.174
      - CONFIG_MSSQL_PORT=49172
      - CONFIG_MSSQL_USERNAME=THANHMINH
      - CONFIG_MSSQL_PASSWORD=123beta456
      - CONFIG_MSSQL_DB_NAME=SOLENH
      - CONFIG_SECRET_SIGN_KEY=secret_sign_key
      - CONFIG_ACCESS_TOKEN_SECRET=access_token_secret
      - CONFIG_REFRESH_TOKEN_SECRET=refresh_token_secret
      - CONFIG_EXPIRE_TIME=3600
      - CONFIG_NODEMAILER_USER=minhcloudinary@gmail.com
      - CONFIG_NODEMAILER_PASSWORD=wenqafmrinypywot
      - CONFIG_REDIS_URL=redis://:redis_demo_password@52.221.246.188:6379